### ISSUE TITLE
Reference parameters

### ISSUE THREAD

**Issue by rachelnertia** [Naios/function2#7]
The following code does not compile on MSVC version 19.12.25830.2 (Visual Studio 2017 15.5.1):

```cpp
int foo(int& i) { return i; }
// ...
fu2::function<int(int&)> f = foo;
```

With the errors:

```
function2.hpp(355): error C2672: 'fu2::v5::detail::invocation::invoke': no matching overloaded function found
...
function2.hpp(355): error C2893: Failed to specialize function template 'unknown-type fu2::v5::detail::invocation::invoke(Callable &&,Args &&...) noexcept(<expr>)'
function2.hpp(355): note: With the following template arguments:
function2.hpp(355): note: 'Callable=int (__cdecl *&)(int &)'
function2.hpp(355): note: 'Args={int}'
```

However, I can get around this using std::reference_wrapper:

```cpp
fu2::function<int(std::reference_wrapper<int>)> f = foo;
```

Is this an issue on other compilers? I thought I'd share my workaround in case others run up against this issue and maybe see if it can be fixed, but I don't have enough template metaprogramming experience to understand what's going wrong here.

**Comment by Naios** [comment]
Ah, sorry that I totally missed this Issue. I wasn't notified through Github.
Thanks for your Issue report. I will take a look at it in the next few days.
